import blog1 from "../public/assets/blogs/blog1.jpg";
import blog2 from "../public/assets/blogs/blog2.jpg";
import blog3 from "../public/assets/blogs/blog3.jpg";
import blog4 from "../public/assets/blogs/blog4.jpg";
import blog5 from "../public/assets/blogs/blog5.jpg";
import blog6 from "../public/assets/blogs/blog6.jpg";
import blog7 from "../public/assets/blogs/blog7.jpg";

export const blogData = [
  {
    id: 1,
    category: "AI",
    title: "Revolutionize Your Business with Our Cutting-Edge",
    description: `Generative AI has revolutionized the world with the introduction of Large Language Models (LLMs). It is such a technology that allows businesses to streamline their work and generate content at a high level. Essentially making businesses a lot better with just one technology implemented.

Not to mention that the content generated by the LLM is done based on prediction due to machine learning and deep learning to understand the words being inputted and created. So, with that many different technologies leading to the creation of LLMs, it is the best innovation in the AI world in a while.

Businesses have understood the value of this and have started to use LLM for a variety of use cases. Whether it be content generation, data analysis, or serving as a base for a chatbot, LLMs are exceptional at doing tedious text related work.

So, let’s try to understand what an LLM is, how it works and why a business should invest in the technology.`,
    img: blog1,
    date: "April 9, 2024",
  },
  {
    id: 2,
    category: "Chatbots",
    title: "New Post 3",
    description: `Generative AI has revolutionized the world with the introduction of Large Language Models (LLMs). It is such a technology that allows businesses to streamline their work and generate content at a high level. Essentially making businesses a lot better with just one technology implemented.

Not to mention that the content generated by the LLM is done based on prediction due to machine learning and deep learning to understand the words being inputted and created. So, with that many different technologies leading to the creation of LLMs, it is the best innovation in the AI world in a while.

Businesses have understood the value of this and have started to use LLM for a variety of use cases. Whether it be content generation, data analysis, or serving as a base for a chatbot, LLMs are exceptional at doing tedious text related work.

So, let’s try to understand what an LLM is, how it works and why a business should invest in the technology.`,
    img: blog2,
    date: "April 9, 2024",
  },

  {
    id: 3,
    category: "Customer Engagement",
    title: "Get Ahead of Your Competition: Our Proven Digital",
    description: `Generative AI has revolutionized the world with the introduction of Large Language Models (LLMs). It is such a technology that allows businesses to streamline their work and generate content at a high level. Essentially making businesses a lot better with just one technology implemented.

Not to mention that the content generated by the LLM is done based on prediction due to machine learning and deep learning to understand the words being inputted and created. So, with that many different technologies leading to the creation of LLMs, it is the best innovation in the AI world in a while.

Businesses have understood the value of this and have started to use LLM for a variety of use cases. Whether it be content generation, data analysis, or serving as a base for a chatbot, LLMs are exceptional at doing tedious text related work.

So, let’s try to understand what an LLM is, how it works and why a business should invest in the technology.`,
    img: blog3,
    date: "April 9, 2024",
  },

  {
    id: 4,
    category: "Healthcare",
    title: "Digital Marketing Made Easy: Let Our Team Handle",
    description: `Generative AI has revolutionized the world with the introduction of Large Language Models (LLMs). It is such a technology that allows businesses to streamline their work and generate content at a high level. Essentially making businesses a lot better with just one technology implemented.

Not to mention that the content generated by the LLM is done based on prediction due to machine learning and deep learning to understand the words being inputted and created. So, with that many different technologies leading to the creation of LLMs, it is the best innovation in the AI world in a while.

Businesses have understood the value of this and have started to use LLM for a variety of use cases. Whether it be content generation, data analysis, or serving as a base for a chatbot, LLMs are exceptional at doing tedious text related work.

So, let’s try to understand what an LLM is, how it works and why a business should invest in the technology.`,
    img: blog4,
    date: "April 9, 2024",
  },

  {
    id: 5,
    category: "Tech",
    title: "Unlock the Power of Digital Marketing: Our Services",
    description: `Generative AI has revolutionized the world with the introduction of Large Language Models (LLMs). It is such a technology that allows businesses to streamline their work and generate content at a high level. Essentially making businesses a lot better with just one technology implemented.

Not to mention that the content generated by the LLM is done based on prediction due to machine learning and deep learning to understand the words being inputted and created. So, with that many different technologies leading to the creation of LLMs, it is the best innovation in the AI world in a while.

Businesses have understood the value of this and have started to use LLM for a variety of use cases. Whether it be content generation, data analysis, or serving as a base for a chatbot, LLMs are exceptional at doing tedious text related work.

So, let’s try to understand what an LLM is, how it works and why a business should invest in the technology.`,
    img: blog5,
    date: "April 9, 2024",
  },

  {
    id: 6,
    category: "AI",
    title: "Drive Traffic and Convert Leads with Our Expert Digital",
    description: `Generative AI has revolutionized the world with the introduction of Large Language Models (LLMs). It is such a technology that allows businesses to streamline their work and generate content at a high level. Essentially making businesses a lot better with just one technology implemented.

Not to mention that the content generated by the LLM is done based on prediction due to machine learning and deep learning to understand the words being inputted and created. So, with that many different technologies leading to the creation of LLMs, it is the best innovation in the AI world in a while.

Businesses have understood the value of this and have started to use LLM for a variety of use cases. Whether it be content generation, data analysis, or serving as a base for a chatbot, LLMs are exceptional at doing tedious text related work.

So, let’s try to understand what an LLM is, how it works and why a business should invest in the technology.`,
    img: blog6,
    date: "April 9, 2024",
  },

  {
    id: 7,
    category: "Business",
    title: "Boost Your Online Presence: Our Top Digital Marketing",
    description: `Generative AI has revolutionized the world with the introduction of Large Language Models (LLMs). It is such a technology that allows businesses to streamline their work and generate content at a high level. Essentially making businesses a lot better with just one technology implemented.

Not to mention that the content generated by the LLM is done based on prediction due to machine learning and deep learning to understand the words being inputted and created. So, with that many different technologies leading to the creation of LLMs, it is the best innovation in the AI world in a while.

Businesses have understood the value of this and have started to use LLM for a variety of use cases. Whether it be content generation, data analysis, or serving as a base for a chatbot, LLMs are exceptional at doing tedious text related work.

So, let’s try to understand what an LLM is, how it works and why a business should invest in the technology.`,
    img: blog7,
    date: "April 9, 2024",
  },
];
